# Generated by Django 5.2.7 on 2025-11-07 08:20

from django.db import migrations
from common.schemas.dynamodb import AttributeDefinition, CreateTableAttr, KeySchema
from common.services.dynamodb import get_dynamodb_service


def create_mail_log_table(apps, schema_editor):
    create_table_attr = CreateTableAttr(
        table_name='mail_log',
        key_schema=[
            KeySchema('task_id', 'HASH'),
        ],
        attribute_definitions=[
            AttributeDefinition('task_id', 'S'),
        ],
    )

    with get_dynamodb_service() as dynamodb_service:
        dynamodb_service.create_table(create_table_attr)
        dynamodb_service.create_ttl('mail_log', 'delete_after')


def delete_mail_log_table(apps, schema_editor):
    with get_dynamodb_service() as dynamodb_service:
        dynamodb_service.delete_table('mail_log')


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_mail_log_table, reverse_code=delete_mail_log_table)
    ]
