# Generated by Django 5.2.7 on 2025-10-30 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='provide',
            new_name='province',
        ),
    ]
