# Generated by Django 5.2.7 on 2025-10-30 07:12

from django.db import migrations, models


def convert_blank_email_to_null(apps, schema_editor):
    User = apps.get_model('account', 'User')
    User.objects.filter(email='').update(email=None)


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_provide_user_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.RunPython(convert_blank_email_to_null, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
