# Generated by Django 5.2.7 on 2025-11-01 17:12

from django.db import migrations

from account.utils.location import refresh_vn_location_data


def init_location_data(apps, schema_editor):
    refresh_vn_location_data()


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_alter_user_email"),
    ]

    operations = [
        migrations.RunPython(init_location_data, reverse_code=migrations.RunPython.noop),
    ]
