# Generated by Django 5.2.7 on 2025-11-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20251101_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(default='User', max_length=128),
        ),
    ]
